apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-otus-auth-db-connection
  labels:
    {{- include "otus-auth.labels" . | nindent 4 }}
stringData: 
  connectionString: Server={{ .Release.Name }}-postgresql;Port=5432;Database=otus;User Id=postgres;Password={{ .Values.postgresPassword }};Timeout=600;Include Error Detail = true