apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user-service-{{ .Release.Revision }}
  labels:
    {{- include "otus-auth.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-user-service-{{ .Release.Revision }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-user-service-{{ .Release.Revision }}
  template:
    metadata:
      name: {{ .Release.Name }}-user-service-{{ .Release.Revision }}
      labels:
        app: {{ .Release.Name }}-user-service-{{ .Release.Revision }}
    spec:
      serviceAccountName: jobs-pods-reader
      initContainers:
        - name: {{ .Release.Name }}-user-service-{{ .Release.Revision }}-init
          image: groundnuty/k8s-wait-for:v2.0
          imagePullPolicy: IfNotPresent
          args:
            - "job"
            - {{ .Release.Name }}-user-service-migrator-{{ .Release.Revision }}
      containers:
        - name: {{ .Release.Name }}-user-service-{{ .Release.Revision }}
          image: kuzindiman/user-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: connectionString
                  name: {{ .Release.Name }}-otus-auth-db-connection
      restartPolicy: Always
      