apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otus-web-app-monitor
  labels:
    release: {{ .Release.Name }}
    {{- include "otus-auth.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-otus-auth-app-{{ .Release.Revision }}
  endpoints:
    - port: web